server:
  port: 9004
spring:
  application:
    name: lagou-gateway
  cloud:
    gateway:
      routes:
        - id: lagou-serivce-user
          uri: lb://lagou-service-user
          predicates:
            - Path=/user/**

        - id: lagou-service-code
          uri: lb://lagou-service-code
          predicates:
            - Path=/code/**


    nacos:
      discovery:
        server-addr: 114.215.180.196:8000
        namespace: lagou-task

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug


